project_id = "vktbkehoymmgvrjujjka"

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.send-alert-email]
verify_jwt = false

[functions.process-community-update]
verify_jwt = false

[functions.run-alert-engine]
verify_jwt = false

[functions.claim-listing]
verify_jwt = false

[functions.verify-claim]
verify_jwt = false

[functions.update-claimed-listing]
verify_jwt = false
